[package]
name = "onebrc_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
memmap2 = "0.9.4"
mimalloc = "0.1.39"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = 'fat'
opt-level = 3
panic = "abort"
strip = "symbols"
